apiVersion: v1
kind: Service
metadata:
  labels:
    app: wecom
    component: wecom
  name: wecom
  namespace: infra
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: wecom
    component: wecom
    tier: backend
  sessionAffinity: None


---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wecom
    component: wecom
    tier: backend
    create_time: <CREATE_TIME>
  name: wecom
  namespace: infra
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: wecom
      component: wecom
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: wecom
        component: wecom
        tier: backend
        create_time: <CREATE_TIME>
    spec:
      containers:
        - env:
            - name: branch
              value: <BRANCH_NAME>
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: hub.test.com/infra-app/wecom-prod:<BUILD_TAG>
          imagePullPolicy: Always
          name: wecom-pod
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
            - name: log-path
              mountPath: "/wecom/logs"
          resources:
            limits:
              cpu: 800m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            # initialDelaySeconds: 70
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 30
            tcpSocket:
              port: 8000
          livenessProbe:
            # initialDelaySeconds: 70
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30
            tcpSocket:
              port: 8000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      nodeSelector:
        devops: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
      volumes:
        - name: tz-config
          hostPath:
            path: /etc/localtime
        - name: log-path
          persistentVolumeClaim:
            claimName: wecom