- op: add
  path: /metadata/annotations/kubernetes.io~1change-cause
  value: image updated to ${build_tag}
- op: add
  path: /metadata/labels/create_time
  value: ${pod_create_time}
- op: add
  path: /spec/template/metadata/labels/create_time
  value: ${pod_create_time}
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: branch
    value: ${branch_name}